// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  foundations: [{ type: 'autogenerated', dirName: 'foundations' }],
  content: [{ type: 'autogenerated', dirName: 'content' }],
}

module.exports = sidebars
