// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  foundations: [{ type: 'autogenerated', dirName: 'foundations' }],
  content: [{ type: 'autogenerated', dirName: 'content' }],
  components: [{ type: 'autogenerated', dirName: 'components' }],
  development: [{ type: 'autogenerated', dirName: 'development' }],
}

module.exports = sidebars
