#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "Pushing commits to the main branch is not allowed. Please create a new branch and submit a Pull Request."
  exit 1
fi
